'use strict';
const ADMIN = { email: 'admin@techx.com', password: 'admin123', name: 'Admin', role: 'admin' };
const PAGE = (() => { const p = location.pathname.split('/').pop() || 'index.html'; if (p === 'dashboard.html') return 'dashboard'; if (p === 'login.html') return 'login'; if (p === 'signup.html') return 'signup'; return 'index'; })();
const SEED_PRODUCTS = [
  { id: 'p1', name: 'Samsung Galaxy S24 Ultra', category: 'mobiles', price: 52000, rating: 4.9, image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&q=80', specs: { RAM: '12GB', Storage: '256GB' }, description: 'The ultimate Samsung flagship.' },
  { id: 'p2', name: 'iPhone 15 Pro Max', category: 'mobiles', price: 65000, rating: 4.8, image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=80', specs: { RAM: '8GB', Storage: '512GB' }, description: "Apple's most powerful iPhone." },
  { id: 'p3', name: 'MacBook Pro 14"', category: 'laptops', price: 89000, rating: 4.9, image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80', specs: { RAM: '18GB', Storage: '512GB SSD' }, description: 'M3 Pro chip performance.' },
  { id: 'p4', name: 'Dell XPS 15', category: 'laptops', price: 72000, rating: 4.7, image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80', specs: { RAM: '16GB', Storage: '1TB SSD' }, description: 'Stunning OLED display.' },
  { id: 'p5', name: 'Sony WH-1000XM5', category: 'accessories', price: 12500, rating: 4.8, image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80', specs: { Battery: '30hr' }, description: 'Industry-best noise cancellation.' },
  { id: 'p6', name: 'Apple AirPods Pro 2', category: 'accessories', price: 9800, rating: 4.7, image: 'https://images.unsplash.com/photo-1603351154351-5e2d0600bb77?w=600&q=80', specs: { Battery: '30hr' }, description: 'Adaptive Audio.' },
  { id: 'p7', name: 'PlayStation 5', category: 'gaming', price: 22500, rating: 4.9, image: 'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=600&q=80', specs: { Storage: '825GB SSD' }, description: 'Next-gen gaming.' },
  { id: 'p8', name: 'Xbox Series X', category: 'gaming', price: 19800, rating: 4.8, image: 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=600&q=80', specs: { Storage: '1TB SSD' }, description: 'Fastest Xbox ever.' }
];
const LS = { get: (k, f = null) => { try { const v = localStorage.getItem(k); return v ? JSON.parse(v) : f; } catch { return f; } }, set: (k, v) => { try { localStorage.setItem(k, JSON.stringify(v)); } catch {} }, remove: (k) => { localStorage.removeItem(k); } };
function ensureProducts() { if (!LS.get('techx_products') || LS.get('techx_products').length === 0) { LS.set('techx_products', SEED_PRODUCTS); } }
function getProducts() { return LS.get('techx_products', SEED_PRODUCTS); }
function saveProducts(p) { LS.set('techx_products', p); }
function getUsers() { return LS.get('techx_users', []); }
function saveUsers(u) { LS.set('techx_users', u); }
function getCart() { return LS.get('techx_cart', []); }
function saveCart(c) { LS.set('techx_cart', c); }
function getLoggedIn() { return LS.get('techx_loggedIn'); }
function setLoggedIn(u) { LS.set('techx_loggedIn', u); }
function logout() { LS.remove('techx_loggedIn'); }
function showToast(msg, type = 'default', duration = 3000) { const stack = document.getElementById('toastStack'); if (!stack) return; const icons = { default: 'fa-circle-check', success: 'fa-circle-check', error: 'fa-circle-xmark', warning: 'fa-triangle-exclamation' }; const toast = document.createElement('div'); toast.className = `toast ${type !== 'default' ? type : ''}`; toast.innerHTML = `<i class="fas ${icons[type] || icons.default}"></i> <span>${msg}</span>`; stack.appendChild(toast); setTimeout(() => { toast.classList.add('out'); toast.addEventListener('animationend', () => toast.remove()); }, duration); }
function renderNavUser() { const el = document.getElementById('navUser'); if (!el) return; const user = getLoggedIn(); if (user) { const initials = user.name.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2); el.innerHTML = `<div class="nav-user-info"><div class="nav-avatar">${initials}</div><span class="nav-name">${user.name.split(' ')[0]}</span></div>${user.role === 'admin' ? '<a href="dashboard.html" class="btn btn-outline btn-sm">Dashboard</a>' : ''}<button class="nav-logout" id="navLogout"><i class="fas fa-sign-out-alt"></i></button>`; document.getElementById('navLogout')?.addEventListener('click', () => { logout(); location.href = 'index.html'; }); } else { el.innerHTML = `<div class="nav-auth-links"><a href="login.html" class="btn btn-outline btn-sm">Login</a><a href="signup.html" class="btn btn-primary btn-sm">Sign Up</a></div>`; } }
function initNavbar() { const hamburger = document.getElementById('hamburger'); const mobileNav = document.getElementById('mobileNav'); hamburger?.addEventListener('click', () => { hamburger.classList.toggle('open'); mobileNav?.classList.toggle('open'); }); window.addEventListener('scroll', () => document.getElementById('navbar')?.classList.toggle('scrolled', window.scrollY > 20), { passive: true }); renderNavUser(); }
function starsHTML(r) { let s = ''; for (let i = 1; i <= 5; i++) { s += i <= Math.floor(r) ? '<i class="fas fa-star"></i>' : (i - r) < 1 ? '<i class="fas fa-star-half-stroke"></i>' : '<i class="far fa-star"></i>'; } return s + `<span>(${r})</span>`; }
function formatPrice(p) { return `EGP ${p.toLocaleString('en-EG')}`; }
function capFirst(s) { return s.charAt(0).toUpperCase() + s.slice(1); }
let activeFilter = 'all', activeSort = 'default', activeSearch = '';
function renderProducts() { const grid = document.getElementById('productsGrid'); const noEl = document.getElementById('noProducts'); if (!grid) return; let prods = getProducts(); if (activeFilter !== 'all') prods = prods.filter(p => p.category === activeFilter); if (activeSearch.trim()) { const q = activeSearch.toLowerCase(); prods = prods.filter(p => p.name.toLowerCase().includes(q) || p.category.toLowerCase().includes(q)); } if (activeSort === 'price-asc') prods = [...prods].sort((a, b) => a.price - b.price); if (activeSort === 'price-desc') prods = [...prods].sort((a, b) => b.price - a.price); if (activeSort === 'rating') prods = [...prods].sort((a, b) => b.rating - a.rating); if (prods.length === 0) { grid.innerHTML = ''; noEl?.classList.remove('hidden'); return; } noEl?.classList.add('hidden'); grid.innerHTML = prods.map((p, i) => `<div class="prod-card" data-id="${p.id}" style="animation-delay:${i * 0.04}s"><div class="pc-img-wrap"><img src="${p.image}" alt="${p.name}" loading="lazy"/><span class="pc-cat">${capFirst(p.category)}</span></div><div class="pc-body"><div class="pc-name">${p.name}</div><div class="pc-stars">${starsHTML(p.rating)}</div><div class="pc-price">${formatPrice(p.price)} <sub>EGP</sub></div><button class="pc-add" data-id="${p.id}"><i class="fas fa-cart-plus"></i> Add to Cart</button></div></div>`).join(''); document.querySelectorAll('.pc-add').forEach(btn => btn.addEventListener('click', e => { e.stopPropagation(); addToCart(btn.dataset.id); })); document.querySelectorAll('.prod-card').forEach(card => card.addEventListener('click', e => { if (!e.target.closest('.pc-add')) openModal(card.dataset.id); })); }
function initShop() { document.querySelectorAll('.ftab').forEach(tab => { tab.addEventListener('click', () => { document.querySelectorAll('.ftab').forEach(t => t.classList.remove('active')); tab.classList.add('active'); activeFilter = tab.dataset.cat; renderProducts(); }); }); document.querySelectorAll('.cat-card').forEach(card => { card.addEventListener('click', () => { activeFilter = card.dataset.filter; document.querySelectorAll('.ftab').forEach(t => t.classList.toggle('active', t.dataset.cat === activeFilter)); renderProducts(); document.getElementById('shop')?.scrollIntoView({ behavior: 'smooth' }); }); }); document.getElementById('sortSelect')?.addEventListener('change', e => { activeSort = e.target.value; renderProducts(); }); const searchInput = document.getElementById('searchInput'); document.getElementById('searchBtn')?.addEventListener('click', () => { activeSearch = searchInput?.value || ''; renderProducts(); }); searchInput?.addEventListener('keydown', e => { if (e.key === 'Enter') { activeSearch = searchInput.value; renderProducts(); } }); document.getElementById('clearSearch')?.addEventListener('click', () => { if (searchInput) searchInput.value = ''; activeSearch = ''; activeFilter = 'all'; document.querySelector('.ftab[data-cat="all"]')?.click(); renderProducts(); }); renderProducts(); }
function addToCart(productId) { const prod = getProducts().find(p => p.id === productId); if (!prod) return; let cart = getCart(); const existing = cart.find(c => c.id === productId); existing ? existing.qty++ : cart.push({ id: prod.id, name: prod.name, price: prod.price, image: prod.image, qty: 1 }); saveCart(cart); updateCartBadge(); renderCartPanel(); showToast(`${prod.name.substring(0, 30)} added to cart!`, 'success'); }
function removeFromCart(productId) { saveCart(getCart().filter(c => c.id !== productId)); updateCartBadge(); renderCartPanel(); }
function changeQty(productId, delta) { let cart = getCart(); const item = cart.find(c => c.id === productId); if (item) { item.qty = Math.max(1, item.qty + delta); saveCart(cart); updateCartBadge(); renderCartPanel(); } }
function updateCartBadge() { const badge = document.getElementById('cartBadge'); if (badge) badge.textContent = getCart().reduce((s, c) => s + c.qty, 0); }
function renderCartPanel() { const body = document.getElementById('cartBody'), footer = document.getElementById('cartFooter'); if (!body) return; const cart = getCart(); if (cart.length === 0) { body.innerHTML = `<div class="cart-empty"><i class="fas fa-cart-shopping"></i><p>Your cart is empty</p><a href="#shop" class="btn btn-primary btn-sm">Start Shopping</a></div>`; if (footer) footer.innerHTML = ''; return; } body.innerHTML = cart.map(item => `<div class="cart-item"><img class="ci-img" src="${item.image}" alt="${item.name}"/><div class="ci-info"><div class="ci-name">${item.name}</div><div class="ci-price">${formatPrice(item.price)}</div><div class="ci-qty"><button onclick="window.changeQty('${item.id}', -1)"><i class="fas fa-minus"></i></button><span>${item.qty}</span><button onclick="window.changeQty('${item.id}', 1)"><i class="fas fa-plus"></i></button></div></div><button class="ci-remove" onclick="window.removeFromCart('${item.id}')"><i class="fas fa-trash"></i></button></div>`).join(''); const subtotal = cart.reduce((s, c) => s + c.price * c.qty, 0); const shipping = subtotal >= 2000 ? 0 : 100; footer.innerHTML = `<div class="cp-summary"><div class="cp-row"><span>Subtotal</span><span>${formatPrice(subtotal)}</span></div><div class="cp-row"><span>Shipping</span><span>${shipping === 0 ? 'Free' : formatPrice(shipping)}</span></div><div class="cp-row cp-total"><span>Total</span><strong>${formatPrice(subtotal + shipping)}</strong></div></div><button class="btn btn-primary btn-full" onclick="checkoutAlert()"><i class="fas fa-lock"></i> Proceed to Checkout</button>`; }
function checkoutAlert() { getLoggedIn() ? showToast('Checkout coming soon!', 'success') : (showToast('Please login to checkout', 'warning'), setTimeout(() => location.href = 'login.html', 1500)); }
function initCart() { const toggle = document.getElementById('cartToggle'), panel = document.getElementById('cartPanel'), overlay = document.getElementById('cartOverlay'), close = document.getElementById('cartClose'); const open = () => { panel?.classList.add('open'); overlay?.classList.add('open'); document.body.style.overflow = 'hidden'; }; const closePanel = () => { panel?.classList.remove('open'); overlay?.classList.remove('open'); document.body.style.overflow = ''; }; toggle?.addEventListener('click', () => panel?.classList.contains('open') ? closePanel() : open()); close?.addEventListener('click', closePanel); overlay?.addEventListener('click', closePanel); updateCartBadge(); renderCartPanel(); }
function openModal(id) { const prod = getProducts().find(p => p.id === id); if (!prod) return; const overlay = document.getElementById('modalOverlay'); document.getElementById('pmImage').src = prod.image; document.getElementById('pmCat').textContent = capFirst(prod.category); document.getElementById('pmName').textContent = prod.name; document.getElementById('pmStars').innerHTML = starsHTML(prod.rating); document.getElementById('pmPrice').textContent = formatPrice(prod.price); document.getElementById('pmDesc').textContent = prod.description || ''; const specsEl = document.getElementById('pmSpecs'); if (prod.specs && Object.keys(prod.specs).length) specsEl.innerHTML = Object.entries(prod.specs).map(([k, v]) => `<div class="pm-spec-item"><small>${k}</small><strong>${v}</strong></div>`).join(''); else specsEl.innerHTML = ''; document.getElementById('pmAddCart').onclick = () => addToCart(prod.id); overlay.classList.add('open'); document.body.style.overflow = 'hidden'; }
function initModal() { const overlay = document.getElementById('modalOverlay'); document.getElementById('modalClose')?.addEventListener('click', () => { overlay.classList.remove('open'); document.body.style.overflow = ''; }); overlay?.addEventListener('click', e => { if (e.target === overlay) { overlay.classList.remove('open'); document.body.style.overflow = ''; } }); document.addEventListener('keydown', e => { if (e.key === 'Escape' && overlay?.classList.contains('open')) { overlay.classList.remove('open'); document.body.style.overflow = ''; } }); }
function initLogin() { if (getLoggedIn()) { location.href = 'index.html'; return; } document.getElementById('loginForm')?.addEventListener('submit', e => { e.preventDefault(); const email = document.getElementById('loginEmail').value.trim(); const pw = document.getElementById('loginPassword').value; if (email === ADMIN.email && pw === ADMIN.password) { setLoggedIn({ ...ADMIN }); showToast('Welcome Admin!', 'success'); setTimeout(() => location.href = 'dashboard.html', 800); } else { alert('Invalid credentials. Use admin@techx.com / admin123'); } }); }
function initSignup() { if (getLoggedIn()) { location.href = 'index.html'; return; } document.getElementById('signupForm')?.addEventListener('submit', e => { e.preventDefault(); const name = document.getElementById('signupName').value.trim(); const email = document.getElementById('signupEmail').value.trim(); const password = document.getElementById('signupPassword').value; if (getUsers().find(u => u.email === email)) { alert('Email already exists'); return; } const users = getUsers(); users.push({ name, email, password, role: 'user', joined: new Date().toLocaleDateString() }); saveUsers(users); alert('Account created! Please login.'); location.href = 'login.html'; }); }
let deleteTargetId = null;
function renderOverview() { const prods = getProducts(), users = getUsers(); const kpiProducts = document.getElementById('kpiProducts'); const kpiUsers = document.getElementById('kpiUsers'); const kpiRating = document.getElementById('kpiRating'); if (kpiProducts) kpiProducts.textContent = prods.length; if (kpiUsers) kpiUsers.textContent = users.length; const avg = prods.length ? (prods.reduce((s, p) => s + p.rating, 0) / prods.length).toFixed(1) : '0'; if (kpiRating) kpiRating.textContent = avg; const recent = document.getElementById('recentProductsList'); if (recent) recent.innerHTML = prods.slice(-5).reverse().map(p => `<div class="rpl-item"><img class="rpl-img" src="${p.image}"/><span class="rpl-name">${p.name}</span><span class="rpl-price">${formatPrice(p.price)}</span></div>`).join('') || '<p style="padding:12px;color:#64748b;">No products yet.</p>'; }
function renderProductsTable(search = '') { const tbody = document.getElementById('productsTableBody'); if (!tbody) return; let prods = getProducts(); if (search) { const q = search.toLowerCase(); prods = prods.filter(p => p.name.toLowerCase().includes(q) || p.category.toLowerCase().includes(q)); } if (prods.length === 0) { tbody.innerHTML = '<tr><td colspan="7" style="text-align:center;padding:32px;">No products found. </td></tr>'; return; } tbody.innerHTML = prods.map((p, i) => `<tr><td>${i + 1}</td><td><img class="dt-img" src="${p.image}" onerror="this.src='https://via.placeholder.com/44'"/></td><td class="dt-name">${p.name}</td><td><span class="dt-cat">${capFirst(p.category)}</span></td><td class="dt-price">${formatPrice(p.price)}</td><td>${starsHTML(p.rating)}</td><td><div class="dt-actions"><button class="btn btn-outline btn-sm" onclick="window.editProduct('${p.id}')"><i class="fas fa-pen"></i> Edit</button><button class="btn btn-outline btn-sm" style="color:#ef4444;border-color:#ef4444;" onclick="window.promptDelete('${p.id}')"><i class="fas fa-trash"></i> Delete</button></div></td></tr>`).join(''); }
function renderUsersTable() { const tbody = document.getElementById('usersTableBody'); if (!tbody) return; const all = [{ name: ADMIN.name, email: ADMIN.email, joined: 'System', role: 'Admin' }, ...getUsers().map(u => ({ ...u, role: 'User' }))]; tbody.innerHTML = all.map((u, i) => `<tr><td>${i + 1}</td><td>${u.name}</td><td>${u.email}</td><td>${u.joined || '—'}</td><td><span class="dt-cat" style="${u.role === 'Admin' ? 'background:#fef3c7;color:#d97706' : ''}">${u.role}</span></td></tr>`).join(''); }
function editProduct(id) { const prod = getProducts().find(p => p.id === id); if (!prod) return; switchTab('add-product'); document.getElementById('editProductId').value = id; document.getElementById('pfName').value = prod.name; document.getElementById('pfCat').value = prod.category; document.getElementById('pfPrice').value = prod.price; document.getElementById('pfRating').value = prod.rating; document.getElementById('pfImage').value = prod.image; document.getElementById('pfDesc').value = prod.description || ''; document.getElementById('formTabTitle').innerHTML = '<i class="fas fa-pen"></i> Edit Product'; document.getElementById('pfSubmit').innerHTML = '<i class="fas fa-save"></i> Update Product'; }
function promptDelete(id) { deleteTargetId = id; document.getElementById('confirmOverlay')?.classList.remove('hidden'); }
function closeConfirm() { document.getElementById('confirmOverlay')?.classList.add('hidden'); deleteTargetId = null; }
function initProductForm() { const form = document.getElementById('productForm'); if (!form) return; document.getElementById('pfCancel')?.addEventListener('click', () => { form.reset(); document.getElementById('editProductId').value = ''; document.getElementById('formTabTitle').innerHTML = '<i class="fas fa-plus-circle"></i> Add New Product'; document.getElementById('pfSubmit').innerHTML = '<i class="fas fa-save"></i> Save Product'; switchTab('products'); }); form.addEventListener('submit', e => { e.preventDefault(); const name = document.getElementById('pfName').value.trim(); const cat = document.getElementById('pfCat').value; const price = parseFloat(document.getElementById('pfPrice').value); const rating = parseFloat(document.getElementById('pfRating').value) || 4.0; const image = document.getElementById('pfImage').value.trim(); const desc = document.getElementById('pfDesc').value.trim(); let valid = true; if (!name) { document.getElementById('pfNameErr').textContent = 'Name required.'; valid = false; } else document.getElementById('pfNameErr').textContent = ''; if (!cat) { document.getElementById('pfCatErr').textContent = 'Category required.'; valid = false; } else document.getElementById('pfCatErr').textContent = ''; if (!price || price <= 0) { document.getElementById('pfPriceErr').textContent = 'Valid price required.'; valid = false; } else document.getElementById('pfPriceErr').textContent = ''; if (!image) { document.getElementById('pfImageErr').textContent = 'Image URL required.'; valid = false; } else document.getElementById('pfImageErr').textContent = ''; if (!valid) return; const editId = document.getElementById('editProductId').value; const prods = getProducts(); if (editId) { const idx = prods.findIndex(p => p.id === editId); if (idx !== -1) prods[idx] = { ...prods[idx], name, category: cat, price, rating: Math.min(5, Math.max(1, rating)), image, description: desc }; showToast('Product updated!', 'success'); } else { const newId = 'p' + Date.now(); prods.push({ id: newId, name, category: cat, price, rating: Math.min(5, Math.max(1, rating)), image, specs: {}, description: desc }); showToast('Product added!', 'success'); } saveProducts(prods); form.reset(); document.getElementById('editProductId').value = ''; renderProductsTable(); renderOverview(); switchTab('products'); }); }
function switchTab(tabId) { document.querySelectorAll('.dash-tab').forEach(t => t.classList.remove('active')); document.querySelectorAll('.dsn').forEach(l => l.classList.remove('active')); const targetTab = document.getElementById(`tab-${tabId}`); if (targetTab) targetTab.classList.add('active'); const targetLink = document.querySelector(`.dsn[data-tab="${tabId}"]`); if (targetLink) targetLink.classList.add('active'); const dtTitle = document.getElementById('dtTitle'); if (dtTitle) dtTitle.textContent = tabId.replace('-', ' ').replace(/\b\w/g, l => l.toUpperCase()); }
function initDashboard() { const user = getLoggedIn(); if (!user || user.role !== 'admin') { showToast('Admin access only.', 'error'); setTimeout(() => location.href = 'login.html', 1000); return; } const initials = user.name.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2); const dtUser = document.getElementById('dtUser'); if (dtUser) dtUser.innerHTML = `<div class="nav-avatar">${initials}</div> <span>${user.name}</span>`; const dashWelcome = document.getElementById('dashWelcome'); if (dashWelcome) dashWelcome.textContent = `Welcome back, ${user.name.split(' ')[0]}! 👋`; document.getElementById('dashLogout')?.addEventListener('click', () => { logout(); location.href = 'login.html'; }); document.querySelectorAll('.dsn[data-tab]').forEach(link => link.addEventListener('click', e => { e.preventDefault(); switchTab(link.dataset.tab); })); document.getElementById('sidebarToggle')?.addEventListener('click', () => document.getElementById('dashSidebar')?.classList.toggle('open')); document.getElementById('goAddProduct')?.addEventListener('click', () => switchTab('add-product')); document.getElementById('goAddProduct2')?.addEventListener('click', () => switchTab('add-product')); initProductForm(); document.getElementById('dashSearch')?.addEventListener('input', e => renderProductsTable(e.target.value)); document.getElementById('confirmDelete')?.addEventListener('click', () => { if (deleteTargetId) { saveProducts(getProducts().filter(p => p.id !== deleteTargetId)); deleteTargetId = null; closeConfirm(); renderProductsTable(); renderOverview(); showToast('Product deleted.', 'success'); } }); document.getElementById('cancelDelete')?.addEventListener('click', closeConfirm); renderOverview(); renderProductsTable(); renderUsersTable(); }
window.editProduct = editProduct; window.promptDelete = promptDelete; window.changeQty = changeQty; window.removeFromCart = removeFromCart; window.addToCart = addToCart; window.checkoutAlert = checkoutAlert;
document.addEventListener('DOMContentLoaded', () => { ensureProducts(); if (PAGE === 'index') { initNavbar(); initShop(); initCart(); initModal(); } else if (PAGE === 'login') initLogin(); else if (PAGE === 'signup') initSignup(); else if (PAGE === 'dashboard') initDashboard(); setTimeout(() => { document.querySelectorAll('.reveal, .reveal-right').forEach(el => { if (el.getBoundingClientRect().top < window.innerHeight) el.classList.add('visible'); }); }, 100); });